CREATE OR REPLACE PACKAGE S242319_PKG IS
	PROCEDURE GET_TABLES_WITHNULL(sheme string); 
END S242319_PKG; 
/


CREATE OR REPLACE PACKAGE BODY S242319_PKG IS

PROCEDURE PRINT_ROW(nom string, table_name string, filler string) IS 
	DELIM CHAR := ' '; 
    NO_COL_WIDTH NUMBER := 3;
	TNAME_COL_WIDTH NUMBER := 20;
	BEGIN 
	DBMS_OUTPUT.PUT_LINE(RPAD(nom, NO_COL_WIDTH, filler) || DELIM || RPAD(table_name, TNAME_COL_WIDTH, filler));
END;
	

PROCEDURE print_header(sheme string) IS
BEGIN
	DBMS_OUTPUT.PUT_LINE('Схема: ' || sheme);
	PRINT_ROW('No.', 'Имя таблицы', ' ');
	PRINT_ROW('-', '-', '-');	
END; 

PROCEDURE GET_TABLES_WITHNULL(sheme string) IS
	CURSOR TRANS_INFO IS
	SELECT DISTINCT ROW_NUMBER() OVER(ORDER BY TABLE_NAME) No,
	TABLE_NAME Tablename 
	FROM ALL_TAB_COLUMNS 
	WHERE OWNER = sheme AND NUM_NULLS <> 0
	GROUP BY TABLE_NAME;
BEGIN
	print_header(sheme);
	FOR ROW IN TRANS_INFO LOOP
		PRINT_ROW(ROW.No, ROW.Tablename, ' ');
	END LOOP;
END;


END S242319_PKG;
/